07/04 10:09:30 - OpenCompass - INFO - Task [Qwen3-8B/lukaemon_mmlu_marketing]
07/04 10:09:34 - OpenCompass - WARNING - Max Completion tokens for /mnt/data/Llmei/data/Qwen/Qwen3-8B is :16384
Traceback (most recent call last):
  File "/home/pyhou/miniconda3/envs/evalscope/lib/python3.10/site-packages/modelscope/utils/import_utils.py", line 451, in _get_module
    return importlib.import_module('.' + module_name, self.__name__)
  File "/home/pyhou/miniconda3/envs/evalscope/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pyhou/miniconda3/envs/evalscope/lib/python3.10/site-packages/modelscope/msdatasets/__init__.py", line 2, in <module>
    from modelscope.msdatasets.ms_dataset import MsDataset
  File "/home/pyhou/miniconda3/envs/evalscope/lib/python3.10/site-packages/modelscope/msdatasets/ms_dataset.py", line 24, in <module>
    from modelscope.msdatasets.utils.hf_datasets_util import load_dataset_with_ctx
  File "/home/pyhou/miniconda3/envs/evalscope/lib/python3.10/site-packages/modelscope/msdatasets/utils/hf_datasets_util.py", line 19, in <module>
    from datasets.data_files import (
ImportError: cannot import name 'get_metadata_patterns' from 'datasets.data_files' (/home/pyhou/miniconda3/envs/evalscope/lib/python3.10/site-packages/datasets/data_files.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pyhou/miniconda3/envs/evalscope/lib/python3.10/site-packages/opencompass/tasks/openicl_infer.py", line 161, in <module>
    inferencer.run()
  File "/home/pyhou/miniconda3/envs/evalscope/lib/python3.10/site-packages/opencompass/tasks/openicl_infer.py", line 79, in run
    self.dataset = build_dataset_from_cfg(self.dataset_cfg)
  File "/home/pyhou/miniconda3/envs/evalscope/lib/python3.10/site-packages/opencompass/utils/build.py", line 13, in build_dataset_from_cfg
    return LOAD_DATASET.build(dataset_cfg)
  File "/home/pyhou/miniconda3/envs/evalscope/lib/python3.10/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/pyhou/miniconda3/envs/evalscope/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/pyhou/miniconda3/envs/evalscope/lib/python3.10/site-packages/opencompass/datasets/base.py", line 12, in __init__
    self.dataset = self.load(**kwargs)
  File "/home/pyhou/miniconda3/envs/evalscope/lib/python3.10/site-packages/opencompass/datasets/mmlu.py", line 22, in load
    from modelscope import MsDataset
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/pyhou/miniconda3/envs/evalscope/lib/python3.10/site-packages/modelscope/utils/import_utils.py", line 434, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/pyhou/miniconda3/envs/evalscope/lib/python3.10/site-packages/modelscope/utils/import_utils.py", line 453, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import modelscope.msdatasets because of the following error (look up to see its traceback):
cannot import name 'get_metadata_patterns' from 'datasets.data_files' (/home/pyhou/miniconda3/envs/evalscope/lib/python3.10/site-packages/datasets/data_files.py)
